/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpelaInRouteImport } from './routes/spela-in'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as ModulerRouteImport } from './routes/moduler'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SpelaInRoute = SpelaInRouteImport.update({
  id: '/spela-in',
  path: '/spela-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulerRoute = ModulerRouteImport.update({
  id: '/moduler',
  path: '/moduler',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/moduler': typeof ModulerRoute
  '/personal': typeof PersonalRoute
  '/spela-in': typeof SpelaInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/moduler': typeof ModulerRoute
  '/personal': typeof PersonalRoute
  '/spela-in': typeof SpelaInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/moduler': typeof ModulerRoute
  '/personal': typeof PersonalRoute
  '/spela-in': typeof SpelaInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/moduler'
    | '/personal'
    | '/spela-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/moduler' | '/personal' | '/spela-in'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/moduler'
    | '/personal'
    | '/spela-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ModulerRoute: typeof ModulerRoute
  PersonalRoute: typeof PersonalRoute
  SpelaInRoute: typeof SpelaInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spela-in': {
      id: '/spela-in'
      path: '/spela-in'
      fullPath: '/spela-in'
      preLoaderRoute: typeof SpelaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moduler': {
      id: '/moduler'
      path: '/moduler'
      fullPath: '/moduler'
      preLoaderRoute: typeof ModulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ModulerRoute: ModulerRoute,
  PersonalRoute: PersonalRoute,
  SpelaInRoute: SpelaInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
